name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          plugin_isocalendar: true
          plugin_languages: true
          plugin_lines: true
          plugin_reactions: true
          plugin_wakatime: true
          token: ${{ secrets.GH_TOKEN }}
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}